name: Update GitHub Forks & HF Downloads

on:
  schedule:
    - cron: "0 0 * * *"  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests huggingface_hub

      - name: Run script
        run: python update_stats.py

      - name: Commit and push if changed
        env:
          GH_TOKEN: ${{ secrets._GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated GitHub forks and Hugging Face downloads" || exit 0
          git push https://x-access-token:${GH_TOKEN}@github.com/ai4protein/ai4protein.git HEAD:main
